package com.project.GameWorld;

public enum ItemType {
    PAPERTOILET,MIUCORPSE,KILLING_GAME_SIMULATOR, LOGIN_LOGOUT_RECORD ,MAP_OF_THE_MANSION ,MAP_OF_THE_WORLD ,TOILET_PAPER ,SIGNBOARD_USED_AS_A_BRIDGE ,MIU_S_AVATAR ,HAMMER ,CELL_PHONE ,LATTICE_NEAR_THE_CHAPEL ,MIU_AND_S_MEETING ,KOKICHI_IN_THE_SALON ,WALL_ADDED_BY_MIU ,SETTING_ON_KOKICHI_S_AVATAR ,AVATAR_ERROR ,DEVICE_INSTRUCTIONS
}
